name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: | 
          ~/.npm
          node_modules
          frontend/node_modules
          backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies
      run: npm install --workspace frontend

    - name: Install backend dependencies
      run: npm install --workspace backend

    - name: Run Lint
      run: npm run lint

    - name: Run Tests (Backend)
      run: npm test --workspace backend

    - name: Run Tests (Frontend)
      run: npm test --workspace frontend

    - name: Run Type Check (Frontend)
      run: npm run type-check --workspace frontend

    - name: Run Type Check (Backend)
      run: npx tsc --noEmit --project backend/tsconfig.json

    - name: Build Frontend
      run: npm run build --workspace frontend

    - name: Build Backend
      run: npm run build --workspace backend
